import { Product } from "./product";

export const Accessories: Product[] = [
    {
        id: 31,
        name: 'Apple Watch Nike Series 5 (GPS + Cellular) with Nike Sport Band',
        price: 529,
        description: "With the Apple Watch Nike Series 5, you can track your workouts and listen to Audio Guided Runs with Nike Run Club. Built-in cellular lets you stream music and stay connected without your phone. You can choose from exclusive Nike sport bands and watch faces that are optimized for the Always-On Retina display (meaning you can always see your screen without having to lift your wrist or tap it).",
        rating: 0,
        img: '../assets/images/accessories-images/apple-watch',
        url: 'https://www.nike.com/t/apple-watch-series-5-gps-cellular-with-nike-sport-band-44mm-silver-aluminum-case-pcw3R0/MX392LLA-043',
        category: 'Accessories',
        category_id: 3,
    },
    {
        id: 32,
        name: 'Nike Sportswear Essentials',
        price: 80,
        description: "With a large laptop sleeve, phone holder and roomy main compartment, the Nike Sportswear Essential Backpack is made with water-repellent details and a rain flap over the zipper to help secure your stuff.",
        rating: 0,
        img: '../assets/images/accessories-images/backpack',
        url: 'https://www.nike.com/t/sportswear-essentials-backpack-Nld6M4/BA6143-072',
        category: 'Accessories',
        category_id: 3,
    },
    {
        id: 33,
        name: 'Nike Brasilia',
        price: 40,
        description: "The durable Nike Brasilia Duffel features a spacious main compartment for all your gear so you can feel prepared. Padded shoulder strap make it carrying comfortable, and multiple exterior pockets provide quick-grab convenience.",
        rating: 4.4,
        img: '../assets/images/accessories-images/brasilia-training-duffel-bag',
        url: 'https://www.nike.com/t/brasilia-training-duffel-bag-medium-qzNQ2p/BA5955-010',
        category: 'Accessories',
        category_id: 3,
    },
    {
        id: 34,
        name: 'Nike Maverick Polarized',
        price: 199,
        description: "A rebel on the outside, the Nike Maverick Polarized Sunglasses are pure performance on the inside. The lightweight frame features innovative temple cushioning and ventilation that ensures you can wear these sunglasses for hours on the course, and off.",
        rating: 0,
        img: '../assets/images/accessories-images/maverick-polarized-golf-sunglasses',
        url: 'https://www.nike.com/t/maverick-polarized-golf-sunglasses-kcB9jq/EV1097-010',
        category: 'Accessories',
        category_id: 3,
    },
    {
        id: 35,
        name: 'Tiger Woods Heritage86',
        price: 35,
        description: "The Tiger Woods Heritage86 Hat elevates off your look with stretchy, sweat-wicking fabric that helps you stay dry and comfortable when your round heats up.",
        rating: 5,
        img: '../assets/images/accessories-images/apple-watch',
        url: 'https://www.nike.com/t/tiger-woods-heritage86-golf-hat-lrwBfN/BQ1309-100',
        category: 'Accessories',
        category_id: 3,
    },
]