import { Product } from "./product";

export const Clothing: Product[] = [
    {
        id: 11,
        name: "Men's Graphic Shorts",
        price: 35,
        description: "The Nike Sportswear Club Shorts blend classic comfort with a bold graphic for street-ready style. Crafted from soft fleece, they've got you covered for all-day wear.",
        rating: 4.8,
        img: 'https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/6ef7989b-b71e-49bd-bb08-25050d5a5e16/sportswear-club-mens-graphic-shorts-hQgvng.jpg',
        url: 'https://www.nike.com/t/sportswear-club-mens-graphic-shorts-hQgvng/BV2721-308',
        category: 'Clothing',
        category_id: 2,
    },
    {
        id: 12,
        name: "Men's Woven Jacket",
        price: 110,
        description: "Inspired by early '90s track jackets, the Nike Sportswear Woven Jacket features color blocking and geometric overlays for bold, throwback style.",
        rating: 0,
        img: 'https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/i1-5496635f-a875-49de-ab9c-b3f3cb193640/sportswear-mens-woven-jacket-25XmvR.jpg',
        url: 'https://www.nike.com/t/sportswear-mens-woven-jacket-25XmvR/CJ4929-674',
        category: 'Clothing',
        category_id: 2,
    },
    {
        id: 13,
        name: "Men's Woven Shorts",
        price: 50,
        description: "Featuring a tonal color-block design, the Nike Sportswear Shorts give you a classic look with simple, street-ready style. Crafted from a lightweight woven fabric and soft mesh lining, they've got you covered for all-day comfort.",
        rating: 4.9,
        img: 'https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/83315694-90e5-4c2c-a5ae-d1c816ba9fd6/sportswear-city-edition-mens-woven-shorts-mTgTN6.jpg',
        url: 'https://www.nike.com/t/sportswear-city-edition-mens-woven-shorts-mTgTN6/CJ4486-010',
        category: 'Clothing',
        category_id: 2,
    },
    {
        id: 14,
        name: 'Pullover Hoodie',
        price: 45,
        description: "A closet staple, the Nike Sportswear Club Fleece Pullover Hoodie combines classic style with the soft comfort of fleece.",
        rating: 4.7,
        img: 'https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/i1-ab7019a5-4e8e-4381-b810-d478c76b26d2/sportswear-club-fleece-pullover-hoodie-Gw4Nwq.jpg',
        url: 'https://www.nike.com/t/sportswear-club-fleece-pullover-hoodie-Gw4Nwq/BV2654-308',
        category: 'Clothing',
        category_id: 2,
    },
    {
        id: 15,
        name: "Men's Full-Zip Hoodie",
        price: 100,
        description: "The Nike Sportswear Tech Fleece Hoodie updates a closet staple with the lightweight warmth of Nike Tech Fleece fabric. Designed with a 2-way zipper, it's a modern take on the classic hoodie.",
        rating: 4.5,
        img: 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/km7yvtzwos6ew2gsuhoj/sportswear-tech-fleece-mens-full-zip-hoodie-PhlsFQ.jpg',
        url: 'https://www.nike.com/t/sportswear-tech-fleece-mens-full-zip-hoodie-PhlsFQ/928483-010',
        category: 'Clothing',
        category_id: 2,
    },
]
