import { Product } from "./product";

export const Shoes: Product[] = [
    {
        id: 1,
        name: "Kyrie 6 'Shutter Shades'",
        price: 130,
        description: 'Inspired by the colorful slatted sunglasses that become popular again in the early 2000s, the Kyrie 6 ‘Shutter Shades’ features a glow-in-the-dark heel and a color-shifting Swoosh that make the shoe pop while nodding to a fun fashion trend of the new millennium.',
        rating: 4.7,
        img: 'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/i1-9093057a-0fd1-47a9-b1f3-4aa1566bc7a0/kyrie-6-shutter-shades-basketball-shoe-TW3wsC.jpg',
        url: 'https://www.nike.com/t/kyrie-6-chinese-new-year-basketball-shoe-TW3wsC/BQ4630-004',
        category: 'Shoes',
        category_id: 1,
    },
    {
        id: 2,
        name: 'Zoom Freak 1',
        price: 120,
        description: "Get your freak on in Giannis Antetokounmpo's debut signature shoe, Nike's first ever for the international basketball sensation. The Zoom Freak 1 has the extra-responsive cushioning, forefoot stability and multidirectional traction needed to complement his freakishly athletic game.",
        rating: 4.5,
        img: 'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/i1-686175a1-22db-4484-8bc0-53c815fcb6fe/zoom-freak-1-basketball-shoe-tmk8Hw.jpg',
        url: 'https://www.nike.com/t/zoom-freak-1-basketball-shoe-tmk8Hw/BQ5422-200',
        category: 'Shoes',
        category_id: 1,
    },
    {
        id: 3,
        name: 'LeBron 17 Low',
        price: 160,
        description: "Fine-tuned with LeBron's ferocious game in mind, the LeBron 17 Low has a sleek, low-top design that features a powerful combination of impact-ready cushioning and responsiveness.",
        rating: 3,
        img: 'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/i1-53dfcfc6-fc68-4f6d-bed3-42c99a469328/lebron-17-low-basketball-shoe-fHcqqM.jpg',
        url: 'https://www.nike.com/t/lebron-17-low-basketball-shoe-fHcqqM/CD5007-001',
        category: 'Shoes',
        category_id: 1,
    },
    {
        id: 4,
        name: 'LeBron 17',
        price: 200,
        description: "The LeBron 17 harnesses LeBron's strength and speed with containment and support for all-court domination. It features a lightweight mix of knit and heat-molded yarns that give each one a durable look and feel. Combined cushioning provides LeBron with the impact support and responsive energy return he needs to power through the long season.",
        rating: 0,
        img: 'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/i1-671f7a5d-a286-463b-a451-b5a38dfc0566/lebron-17-basketball-shoe-2PjnVK.jpg',
        url: 'https://www.nike.com/t/lebron-17-basketball-shoe-2PjnVK/CD5056-400',
        category: 'Shoes',
        category_id: 1,
    },
    {
        id: 5,
        name: 'PG 4',
        price: 110,
        description: "Paul George is the rare high-percentage shooter who's also a coach's dream on D. Designed for his unrivaled 2-way game, the PG 4 unveils a new cushioning system that's lightweight, articulated and responsive, ideal for players like PG who go hard every play.",
        rating: 4,
        img: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/i1-73b6c002-4dcc-4ed1-b05c-54b9082557ed/pg-4-basketball-shoe-tszRns.jpg",
        url: 'https://www.nike.com/t/pg-4-basketball-shoe-tszRns/CD5079-001',
        category: 'Shoes',
        category_id: 1,
    },
];